parse_config:
  zmk_remove_keycode_prefix: ["SEM_", "SED_"]
  raw_binding_map:
    "&td0": "1x:ALT 2x:WIN"
  zmk_keycode_map:
    # Custom for this repo
    AE: "Å"
    AA: "Ä"
    OO: "Ö"
    # Defaults from https://github.com/caksoylar/keymap-drawer/blob/main/keymap_drawer/config.py#L420-L485
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: "$"
    DLLR: "$"
    PERCENT: "%"
    PRCNT: "%"
    CARET: "^"
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: "("
    LPAR: "("
    RIGHT_PARENTHESIS: ")"
    RPAR: ")"
    EQUAL: "="
    PLUS: "+"
    MINUS: "-"
    UNDERSCORE: "_"
    UNDER: "_"
    SLASH: "/"
    FSLH: "/"
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH: "\\"
    BSLH: "\\"
    PIPE: "|"
    NON_US_BACKSLASH: "\\"
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON: ";"
    SEMI: ";"
    COLON: ":"
    SINGLE_QUOTE: "'"
    SQT: "'"
    APOSTROPHE: "'"
    APOS: "'"
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ","
    LESS_THAN: "<"
    LT: "<"
    PERIOD: "."
    DOT: "."
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET: "["
    LBKT: "["
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET: "]"
    RBKT: "]"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE: "`"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"
